package com.ALS.als_testoftheday1;

import java.util.Calendar;
import java.util.GregorianCalendar;

import android.os.Bundle;
import android.support.v7.app.ActionBar;
import android.support.v7.app.ActionBarActivity;
import android.view.Window;
import android.view.WindowManager;
import android.widget.TextView;

public class DoYouKnow extends ActionBarActivity {

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
//		this.requestWindowFeature(Window.FEATURE_NO_TITLE);

		this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);

		setContentView(R.layout.activity_do_you_know);
		ActionBar actionBar = getSupportActionBar();
		actionBar.hide();
		
TextView quoteOfTheDay = (TextView)findViewById(R.id.textViewDidYouKnow);
		
		GregorianCalendar gc = new GregorianCalendar();
		int day = gc.get(Calendar.DAY_OF_YEAR);
		
		quoteOfTheDay.setText(didyouknow[day]);
		
	}
	
	 String didyouknow[] = {
				"In about 5 b yrs, Sun will burn out its stock of hydrogen and will turn  into a Red Giant. It will then have swelled 100 times its diameter and will occupy 25 % of the horizon and the humans would have migrated to some other planetary system in a nearby galaxy. WOW!!!",
				 "The Great Wall of China is the only man-made structure visible from the Moon",
				 "Great Red Spot on Jupiter is an enormous eddy in turbulent cloud cover",
				 "Brightest star outside solar system is Sirius, also called the Dog Star",
				 "Closest star to the Earth is Sun and not Proxima Centauri",
				 "Closest star to our solar system is Proxima Centauri, also called Alfa Centauri at a distance of 4.3 light years",
				 "Everyone knows the 12 sun signs. Do you know the 13th! It's Ophucus",
				 "Shape of Earth can be best described as Geoid",
				 "Earth’s rotational velocity at the equator is 	  1690 km/hr",
				 "A solar day is greater than a sidereal day by 	  4 minutes",
				 "Point in the orbit of Moon when it’s farthest from Earth 	  Apogee",
				 "Each degree of latitude equals 	5. »111 km",
				 "A person crossing International Date Line from East to West	  loses one day",
				 "The sun is vertically overhead at the equator on	 March 21(spring equinox)",
				 "	Most destructive of weather disturbances...	Tornado",
				 "Climatic type with minimum annual temperature range...	 Hot, Wet Equatorial",
				 "A ‘wet day’ is ... 	when the amount of rainfall is at least 1mm",
				 "If xoC = xoF; x = ...	-400 C/5=F-32/9",
				 "The average albedo of the Earth... 	35%",
				 "Winter concentration of rainfall characteristic of... 	Mediterranean climate",
				 "Roaring Forties, Furious Fifties and Shrieking Sixties are westerlies of...	Southern hemisphere",
				 "South American country which is a member of OPEC ...	Venezuela",
				 "Outport of Sao Paulo ...	Santos",
				 "Trees that yield quinine... 	  Cinchona",
				 "Coffee pot of the world... 	Brazil",
				 "Legal capital of Bolivia ...	Sucre",
				 "Administrative capital of Bolivia ... 	La Paz",
				 "Southern most inhabited city in the world ...	Punta Arenas,ChileThe most densely populated country of the Americas...	Barbados",
				 "Central American countries arranged from N to S... 	Belize, Guatemala, "
				 +"Honduras,  El Salvador, Nicaragua, "
				 +"Costa Rica & Panama",
				 "The only capital city of a Central American country		having a coastal location...	Panama city ",
				 "Panama was once a province of...	 Colombia",
				 "Mosquito coast is located in... 	Nicaragua",
				 "Old capital of  Belize... 	Belize city",
				 "The capital of Costa Rica, Honduras and El Salvador... 	San Jose, "
				 +"Tegucigalpa, San Salvador",
				 "US’ states in descending order of area...  	Alaska> Texas> California >Montana",
				 "Smallest state of USA...	Rhode island",
				 "Smallest administrative unit of USA... 	Distt. of Columbia",
				 "Most populated state of USA ...	California",
				 "Longest river of USA ...	Mississippi- Missouri",
				 "Highest peak in N. America... 	Mt. Mckinley",
				 "Highest peak in conterminus USA..	Mt. Whitney",
				 "The South African town where Mahatma Gandhi, on being ",
				 "thrown out of the train, waved to fight racism...	Pietermoritzberg",
				 "The Kalahari desert is situated between the rivers...	Orange and Zambezi ",
				 "The country having highest death rate and least life expectancy in world...	Sierra Leone  ",
				 "A hot local wind blowing from Sahara to Mediterranean ... 	Sirocco",
				 "The oldest surviving African language ...	Swahili	",
				 "Most of Kalahari lies in  ...	Botswana",
				 "Australia is ...  of all continents 	Smallest",
				 "The largest city of Australia ...	Sydney",
				 "Flightless bird of Australia ...	Emu",
				 "The New Zealander who was the 1st to scale Mt. Everest ...	Edmund Hillary",
				 "Plains of New Zealand famous for the dairy industry ...	Taranaki",
				 "Region of inland drainage in Australia ...	Lake Eyre",
				 "Natural fountains in Australia...	Great Artesian Wells",
				 "	The coldest place in the Northern Hemisphere... 	Verkhoyansk (Russia) ",
				 "The strait that separates Hokkaido and Honshu islands of Japan... 	Tsugaru strait ",
				 "The Manchester of Japan... 	Osaka ",
				 "The tough and fearless people, Kirghiez are also known as... 	Tartar ",
				 "The famous variety of Orange found in Israel... 	Jaffa ",
				 "The discontiguous city of Russia... 	Kaliningrad ",
				 "In descending order of size, the four islands of Japan... 	I- Honshu, II-Hokkaido, III-Kyushu, IV-Shikoku",
				 "The White City of North... 	Helsinki (Finland)",
				 "The city known as 'the key to the Baltic'... 	Copenhagen ",
				 "The world’s most northerly capital... 	Reykjavik (Iceland)",
				 "The only fibre crop of Europe which is used for making Linen... 	Flax ",
				 "The highest peak of the Alps...	Mt. Blanc (7807 m)",
				 "The highest peak of Europe... 	Mt. Elbrus (5633 m) ",
				 "The mountain forming the boundary between France and Spain...  	Pyrenees",
				 "The planets according to their size in the descending order are Jupiter, Saturn, Uranus, Neptune, Earth, Venus, Mars, Mercury and Pluto. An acronym to assist – ‘Just Show Us Nine Educated & Versatile Mothers Measuring Planets’",
				 "Ecliptic is an imaginary annual path of Sun across the sky",
				 "Heliocentric view was first suggested by Copernicus",
				 "Galaxies are also called Island Universe",
				 "Existence of galaxies beyond Milkyway was first demonstrated by Edwin Hubble ",
				 "Comets in Latin mean ‘Long Haired’, and not all comets have ‘hair’",
				 "A Jet capable of moving at a speed of 1000 kmph would need about 17 years of nonstop flying to reach the Sun",
				 "The nearest galaxy, Andromeda is 22,00,000 Light Years away",
				 "Largest meteorite impact is in Podkamennaya Tunguska River in Siberia. The explosion was of the order of 10 to 15 megatons of TNT and devastated an area of 3900 km2",
				 "Largest crater known to have formed by a meteorite is the Coon Butte or Barringer Crater in US. Lonar Lake in Buldana district of Maharashtra is the largest meteoric crater lake in India",
				 "The theory of Panspermia maintains that life on earth was seeded from space and that life’s evolution to higher forms depends on complex genes, including those of viruses and diseases, that earth receives from space from time to time",
				 "Prime cause behind Earthquakes	Dislocation along faults",
				 "Elements constituting Earth’s crust in terms of decreasing abundance           	  O(47%),Si(28%),Al(8%),Fe(5%)",
				 "Mumbai is 18.550 north of equator. Distancewise it equals	»2059 km",
				 "Point on Earth’s surface vertically above the seismic focus	Epicentre",
				 	"Circum-Pacific belt is called Ring of Fire because	> 80% of active volcanoes are concentrated here",
				 "When it’s noon in London, the local time for a place 900west of it will be	  6 A.M",
				 "Lighthouse of the Mediterranean 	Mt. Stromboli",
				 "Earth’s interior has a layered structure because of 	Density differentiation   ",
				 "The intensity of earthquake waves is recorded by 	  Seismograph",
				 "Continental Drift Theory was given by 	Alfred Wegener",
				 	"Meridian accepted as the Indian Standard Time	82 ½0E, passing through Allahabad  ",
				 	"A meteoric crater lake found in India 	Lonar in Maharashtra",
				 "Mohorovicic discontinuity separates 	Crust and Mantle",
				 "Gigantic seismic sea-waves are called 	Tsunamis",
				 "Earth’s tilted axis causes 	Seasons",
				 "Hardest mineral …… and softest mineral...	  Diamond (10 on Moh’s scale); Talc(0 on Moh’s scale)",
				 "Theory that considers Earth’s lithosphere as fractured along several faults	Plate Tectonics",
				 "Seismic waves transverse in nature which do not pass through molten outer core	 ‘S’ waves",    
				 "Gutenberg discontinuity separates 	Mantle and Core",
				 "Theory that explains Earthquakes 	Elastic Rebound Theory",
				 "Earth’s magnetic north and south poles are located on  Prince of Wales Is. in N Canada (700N1000W); South Victoria  Land in  Antarctic (680S1430E)",
				 "Layer beneath the lithosphere capable of flowing under stress	Asthenosphere",
				 "IST is ahead of GMT by 	30.  5 ½ hours",
				 "Line joining places that experience earthquake at the same time 	Homoseismal Line",
				 "The only active volcano in India	Barren Island, Andaman & Nicobar Is.",
				 "Seismic waves that cause maximum destruction 	 ‘L’  (long) waves",
				 "The antipodal point of 100N 1250E is 	  100S 550W",
				 	"The equatorial bulge of Earth is due to 	Centrifugal force of Earth’s rotation",
				 "Magnitude of an earthquake is measured on 	Richter scale",
				 "Earth is round was first theorised by 	Plato ",
				 "The recent earthquake in Gujarat occurred due to 	Dislocation along Allah bund fault in Sind, Pakistan",

				 
				 
				 
				 
				 "	The mountain forming the boundary between France and Germany... 	Vosges",
				 "	The mountain which separates France from Italy... 	Alps ",
				 "	The Ruhr is a small right bank tributary of... 	Rhine ",
				 "	Two important ancient cities of Germany situated along the river Elbe... 	Leipzig, Dresden   ",
				 "	The city of Germany which is the centre for art and culture... 	Munich ",
				 "	The major ice-free port along the Arctic coast... 	Murmansk",
				 "	The Manchester of Italy... 	Milan ",
				 "	The Detroit of Italy... 	Turin ",
				 "	The world’s largest cutlery town... 	Sheffield ",
				 "	The most important fishing ground of UK... 	Dogger Bank", 
				 "	A large mountain mass with one or two summits... 	Massif", 
				 "	A narrow gate between the Vosges and the Jura through which the river Rhine passes... 	Burgundy Gate ",
				 "	The longest river of Europe... 	Volga ",
				 "	The low countries... 	Belgium, Netherlands, Luxemburg ",
				 "	The three CIS countries which are known as Baltic States... 	Estonia, Lithuania, Latvia",
				 "	Big embankments built along the sea front to protect the land from the sea... 	Dykes ",
				 "	The land which is reclaimed from the sea by making dykes... 	Polders ",
				 "	The city of five ports... 	Moscow ",
				 "	The second largest country in Europe, next only to Russia... 	France ",
				 "	More than 90% of iron ore of France comes from... 	Lorraine field ",
				 "	The silk industry of France is located in... 	The Rhone valley ",
				 "	The biggest and the richest coal producing area of Europe... 	Ruhr", 
				 "	Besides Ruhr, the other two important coal fields of Germany...	Saar, Saxony",      
				 "	The Iron ore in Germany is mainly found in... 	Bavaria", 
				 "	The country of Europe having maximum coniferous trees... 	Sweden ",
				 "	The canal which Joins Baltic Sea with North Sea... 	Kiel canal ",
				 "	The city of Russia on the bank of the Angara river having world’s tallest hydel power scheme... 	Brotsk",
				 "	The Bay of Biscay separates... 	France and Spain ",
				 "	The key to the Mediterranean... 	Strait of Gibralter ",
				 "	The Bosporus strait separates... 	Istanbul and Anatolia Peninsula ",
				 "	The longest river of Russia... 	Ob-Irtysh  ",
				 "	The biggest producer of lignite coal in the world... 	Germany ",
				 "	The famous dam of Europe, Genissiat has been constructed on river... 	Rhone ",
				 "	The famous city situated in the island of Sisly... 	Catania ",
				 "	An island of Italy in the Mediterranean Sea... 	Sardinia ",
				 "	The most important city of Italy on the coast of Adriatic sea... 	Venice",
				 "	The most important town for wine making and food processing... Naples",
				 "	The light house of Mediterranean Sea... 	Mt. Stromboli ",
				 "	Rome is situated on the bank of river...	Tibre ",
				 "	The canal which connects Black Sea and Caspian Sea...	Volga-Don Canal ",
				 "	The world’s largest gas field... 	Urengoy ",
				 "	The Detroit of Russia... 	Nizhniy Novgorod ",
				 "	The highest peak of CIS countries... 	Communism Peak (7495 m – Tajikistan) ",
				 "	The Manchester of Germany... 	Munchengladbach",
				 "	The measure in woollen textile centres in the France are... 	Roubaix, Tourwing",
				 "	The industrial heart of France... 	Paris",
				 "	The two cities in Italy known for the production of motor cycles... 	Pedua, Bologna     ",
				 "	The most important port on the west coast of UK... 	Liverpool ",
				 "	The land of forests and lakes... 	Finland ",
				 "	The Great Silk producing city of France... 	Lyons ",
				 "	The famous variety of orange found in Spain... 	Seville ",
				 "	The temperate grassland of Hungary... 	Pustaz ",
				 "	The Sirocco-hot, dry & dusty wind in Spain is known as... 	Levechee",
				 "	The smallest sovereign and an independent state of world... 	Vatican city ",
				 "The country having highest per capita Hydel power output in the world... 	Norway  ",
				 "	The two island countries in Mediterranean Sea... 	Corsica and Cyprus",
				 
				 
				 
				 
				 
				 
				 
				 
				 "	Southernmost tip of Africa ...	Cape of Agulhas",
				 "	The highest peak in Africa ...	Mt Kilimanjaro",
				 "	City at the confluence of Blue and White Nile ...	Khartoum",
				 "	The hottest place in the world ...	Al-Azizhiya, Libya",
				 "	The three Maghreb Republics ...	Morocco, Algeria, Tunisia",
				 "	Source of Blue Nile ... and White Nile ...	L Tana, L Victoria",
				 "	The Little  and the Great Bitter lakes are along ...	Suez Canal",
				 "	A large geographically disadvantaged state ...	Zaire",
				 "	The lowest point in Africa ...	Lake Assal, Djibouti",
				 "	The nomadic herders of Sahara ...	Tuaregs",
				 "	The main entrepot of E Africa ...	Zanzibar",
				 "	A large lake in East Africa not lying in the Great Rift valley ...	Lake Victoria",
				 "	A region of inland drainage ...	Lake Chad",
				 "	Seat of legislature of S Africa ... 	Cape Town",
				 "	Natural region with the greatest biodiversity ...	Rain Forests",
				 "	Judicial capital of S Africa ...	Bloemfontein",
				 "	Four most populous countries in descending order ...	I.Nigeria II.Egypt III.Ethiopia IV.Zaire",
				 "	The temperate grassland of S Africa ...	High Veld",
				 "	Countries which form the Horn of Africa ...	Ethiopia, Somalia, Djibouti",
				 "	Nubian desert lies in ...	Egypt",
				 "	The only river that crosses the equator twice ...	River Zaire",
				 "	Aborigines of upper Nile ...	River Zaire",
				 "	Administrative capital of S Africa ...	Pretoria",
				 "	Land of Oil Palm ...	Nigeria",
				 "	Four largest countries in decreasing order of area ...	I.Sudan II.Algeria III.Zaire III.Libya",
				 "	Land of Gold and Diamonds ...	South Africa",
				 "	New capitals of Nigeria & Tanzania ...	Abuja, Dodoma",
				 "	Clove Bowl of the World ...	Zanzibar & Pemba",
				 "	A hot local wind blowing from Sahara to Guinea coast ...	Harmattan",
				 "	Lake Nasser is on ...	River Nile",
				 "	River boundary between S Africa and Botswana ...	River Limpopo",
				 "	Akosombo dam is on ...	River Volta",
				 "	Largest waterfall in the world...	Victoria Falls",
				 "	Victoria falls are on ...	River Zambezi",
				 "	Two countries of Africa that were never colonized ...	Ethiopia, Liberia",
				 "	Falls discovered by Livingstone ...	Victoria Falls",
				 "	Kimberley is famous for ...	Diamond",
				 "	Witwatersrand is famous for ...	Gold",
				 "	African country with the best quality magnetite ore ...	Liberia",
				 "	Pastoral tribe of Kenya ...	Masai",
				 "	R Orange is a boundary between ...	S Africa & Namibia",
				 "	A new country carved out of Ethiopia during 1990s ...	Eritrea",
				 "	Lourenco Marques was renamed as ...	Maputo",
				 "	S African farmer of Dutch descent...	Boer",
				 "	Countries bordering Lake Victoria ...	Tanzania, Kenya, Uganda",
				 "	Gate of Tears ...	Bab-el-Mandeb",
				 "	A highly nutritious crop of Ethiopian highlands ...	Teff",
				 "	Most tropical of all continents ...	Africa",
				 "	Place of origin of Coffee ...	Ethiopia",
				 "	A flightless bird of Kalahari desert ...	Ostrich",
				 "	Eastern most terminus of Tanzara railway which begins from Katanga mineral belt...	Dar-es-Salam",
				 "	Country facing the strait of Bab-el-Mandeb ...	Djibouti",
				 "	Country with maximum HEP potential in Africa ...	Zaire",
				 "	Gold, Ivory, Slave and Grain coasts, arranged west to east ...	Grain, Ivory, Gold, Slave coast",
				 "	The religion followed by many tribes in Africa which is based on love and respect of nature ...	Animism", 
				 "	The Victoria Fall was discovered by ...	David Livingston", 
				 "	The policy of segregating people on the basis of their race or their colour of skin ...	Apartheid", 
				 "	The Pastoral tribe of Kenya and Tanzania ...	 Masai", 
				 "	The famous Cobora Bassa Dam is on the river ...	Zambezi", 
				 "	The famous Kainji Dam is on the river ...	Niger", 
				 "	The river forming the boundary between Zambia and Zimbabwe ...	Zambezi", 
				 "	The only river to cross the Tropic of Capricorn twice ...	Limpopo", 
				 "	The hot dry wind blowing in the South Eastern part of South Africa ...	Berg", 
				 "	The famous Copper Mines of Zaire ...	Lubumbashi",
				 "	The famous Copper and Cobalt Mines of Zaire-Zambia ...	Katanga",
				 "	The Ngana, tropical disease of cattle in Africa is carried by... 	Tsetse fly", 
				 "	The Coal Mines of Zimbabwe ...	Wankee",
				 "	The Sirocco winds in Libya is known as ...	Gibli",        
				 "	The leading producer of mineral oils in Africa is ...	Nigeria", 
				 "	The largest producer of Sisal in Africa is ...	Tanzania", 
				 "	The Desert in the North East of Sudan ...	Nubian Desert", 
				 "	The Mangroves Vegetation in Africa is found ...	Along the Gulf of Guinea", 
				 "	The largest producer of Coffee in Africa... 	Liberia", 
				 "	The Nomadic hunters and food gatherers of Kalahari Desert... 	Bushman ",
				 "	The man made canal which acts through the isthmus between Egypt and Sinai Peninsula... 	Suez Canal",

				 
				 
				 
				 
				 
				 
				 
				 "	Hollywood is in the state of... 	California",
				 "	The first President of the US... 	George Washington",
				 "	Great Lakes arranged from West to East... 	Superior, Michigan, Huron, Erie and Ontario",
				 "	The Great Lakes lying entirely in USA...	Michigan",
				 "	The Latitude dividing USA and Canada... 	490 N",
				 "	The head office of the software giant Microsoft is in... 	Seattle",
				 "	The Canadian National Railway connects... 	Halifax to Prince Rupert in British Columbia", 
				 "	Mediterranean type of climate is found in... 	California",
				 "	The confluence of Mississippi and Missouri... 	St.Louis",
				 "	The busiest inland waterway of N. America... 	St. Lawrence",
				 "	Damodar Valley Corp. of India on the lines of... 	Tennessee Valley Corp. ",
				 "	The 49th and 50th States of USA are... 	Alaska and Hawaii",
				 "	The ‘Old Faithful’ Geyser is in...	Yellowstone National Park, Wyoming",
				 "	The largest importer and consumer of oil... 	USA",
				 "	Country generating the largest amount of hydroelectric power as % of total power produced... 	Canada",
				 "	Chicago is located on...	 Lake Michigan", 
				 "	Niagra Falls lie between... 	Lakes  Erie and Ontario",
				 "	The canal joining lakes Superior and Huron... 	 Soo canal", 
				 "	The canal joming lakes Erie and Ontario... 	Welland canal", 
				 "	The ‘Big Apple’ describes the city of...	New York",
				 "	North America’s largest urban agglomeration... 	New York",
				 "	The rocket launching centre of USA...	 Cape Kennedy, Florida",
				 "	Busiest airport of the US...	 J F Kennedy Airport, New York",
				 "	The country having won the Davis Cup maximum no. of times... 	USA",
				 "	National sport of USA...	 Baseball",
				 "	National anthem of the US...	 The Star Spangled Banner",
				 "	The driest and the hottest place in USA... 	Death Valley",
				 "	The most recent federal territory of Canada...	Nunavut",
				 "	The number of provinces and  federal territories in Canada...	10 & 3  respectively",
				 "	The capitals of the provinces of Ontario, Alberta, Nova Scotia are... 	Toronto, Edmunton and Halifax",
				 "	The largest province of Canada...	Quebec",
				 "	Maritime provinces of Canada include... 	Newfoundland, New Brunswick, Nova Scotia  and Prince Edward Island",
				 "	The most populated province of Canada... 	Ontario",
				 "	The largest city of Canada... 	Toronto",
				 "	The smallest province of Canada... 	Prince Edward Island",
				 "	Canada is the largest producer of... 	Paper and pulp",
				 "	Highest tidal range is experienced in...	Bay of Fundy",
				 "	The ‘Detroit of Canada’...	Windser",
				 "	The ‘Birmingham of Canada’... 	Hamilton",
				 "	The  Sudbury mines in Canada are famous for... 	Lead, Zinc & Silver",
				 "	The Strait separating N America from Greenland... 	Davis Strait",
				 "	The Canadian Pacific Railway runs between... 	St. John’s in New Brunswick and Vancouver",
				 "	The most famous Aircraft manufacturing Centre of the USA...	Seattle",
				 "	Death valley is situated along the river...	Colorado",
				 "	Fort worth and Dallas are called 'Twin Cities' are situated at the bank of river...	Trinity", 
				 "	Washington DC is located on the bank of river...	Potomac", 
				 "	The two provinces of Canada from where 75% of mineral oil comes... 	Alberta and Saskatchewan", 
				 "	The famous Hoover dams is on river... 	Colorado", 
				 "	The country that leads in production of fine paper from grasses... 	USA",
				 "	The leading producer of Newsprint and Pulp in the world... 	Canada", 
				 "	The Strait of Florida Separates... 	USA and Cuba",
				 "	The Magnetic North Pole located on... 	Prince of Wales Island (˜700N 1000W) ",
				 "	The largest consumer and importer of mineral oil in the world... 	USA",
				 "	Canada’s smallest and most densely populated province... 	Prince  Edward Island", 
				 "	The last province to Join Canada in 1949... 	Newfoundland", 
				 "	The most famous Industrial Centre of USA having specialization in Automobile tyres... 	Akron", 
				 "	An intensely cold and strong wind accompanied by falling snow bund in northern N. America... 	Blizzard", 
				 "	Iron and steel capital of the world... 	Pittsburgh", 
				 "	Fall live town, also called Quaker city... 	Philadelphia",
				 "	The shape of the famous corn belt of USA is... 	Rectangular", 
				 "	The first census in the USA was held in... 	1790",
				 "	The lowest point in the USA is... 	The Death Valley (86 m below sea level) ",
				 "	The city of Golden Gate... 	San Francisco", 
				 "	Mackenzie, the longest river of Canada drains into... 	Beaufort Sea", 
				 "	The state of USA which is the leading producer of cotton... 	Texas", 
				 "	The representative station of Laurentian type of climate in N. America... 	Toronto",    
				 "	The type of delta formed by the river Mississippi in the Gulf of Mexico... 	Bird foot type", 
				 "	The area of inland drainage in the N. America... 	The Great Basin area", 
				 "	Two most prominent lakes of the Yukon Plateau... 	1. Great Bear Lake  2. Great Slave Lake", 
				 "	Biggest naval and fishing port on the pacific coast... 	Victoria",
				 "	The state of USA in which the famous Yellow Stone National Park is situated...	 Wyoming", 
				 "	The capital of Hawai and known as 'the cross roads of pacific',... 	Honolulu",

				 
				 
				 
				 
				 
				 
				 
				 "	Southern most inhabited city in the world ...	Punta Arenas,Chile",
				 "	The Latin languages ...	 French, Italian, Portuguese, Spanish",
				 "	World’s largest exploitable reserves of copper ...	Chile", 
				 "	Most mineral rich state of Brazil ...	Minas Gerais", 
				 "	Strait between South America and Antarctica ... 	Drake Passage",
				 "	Driest place on earth ... 	Iqique,Atacama",
				 "	People of mixed European and American Indian ancestry who work on cattle farms ...	Gauchos",
				 "	South America’s largest steel making facility... 	Tubarao, South Brazil",
				 "	Coffee plantations of Brazil are called ...	Fazendas",
				 "	Land locked countries of South America  ...	Bolivia, Paraguay",
				 "	Countries in descending order of population ...  	I.Brazil II. Columbia  III.Argentina IV.Peru",
				 "	Trans-Andean railways connects ...	Buenos Aires and  Valpariso",
				 "	Tropical grasslands of  South  America...	Llanos and Campos",
				 "	Bolivia is named after ...	Simon Bolivar", 
				 "	Hot  winds  blowing down the Andes in Argentina ...	Zonda",
				 "	Temperate Grasslands of Argentina ...	Pampas",
				 "	A violent cold wind in Argentina and Uruguay ...	Pampero",
				 "	Angel falls, the  highest in the world is on ...     	Orinico river, Venezuela",
				 "	A nutritious leguminous grass of Pampas	Alfa-Alfa",
				 "	Lake Maracaibo, famous for crude oil is in... 	    Venezuela",
				 "	Kouro, the French satellite launching station is in...    	French Guiana",
				 "	Caliche (Sodium Nitrate) is found in...	Atacama Desert",
				 "	South American countries bordering Caribbean Sea ... 	Colombia,  Venezuela, Guyana, Surinam, French Guiana &  Brazil",
				 "	Largest tributary of Amazon ...	Madeira",
				 "	Highest peak of South America ...	Mt Aconcagua",
				 "	Argentinian ranches are called...	Estancias",
				 "	Largest city of South America ...	Sao Paulo",
				 "	Lightest wood  that is found only  in South America ... 	  Balsa",
				 "	Highest navigable lake in the world ...	Titicaca",
				 "	Only country through which both equator and one of the tropics pass ...	Brazil", 
				 "	South American countries with coasts along both Pacific and  Atlantic oceans ...	Colombia, Chile", 
				 "	Country with the largest reserves of hardwood ...	Brazil",
				 "	Copper capital of the world ...	Chuquicamata",
				 "	Official language of Brazil ...	Portuguese",
				 "	Countries in descending order of size ...	I.Brazil II. Argentina III.Peru IV.Columbia",
				 "	Brazil shares its boundary with all South American  countries except ...	Chile and  Equador", 
				 "	Buffer states between Argentina & Brazil ... 	Paraguay, Uruguay and  Bolivia",
				 "	Coffee soils of Brazil ...	Terra Roxa",
				 "	The highest active volcano in the world 	Mt Ojas del Salado", 
				 "	The flightless bird of South America 	Emu",
				 "	The largest bird of prey in the world 	Candor", 
				 "	Dangerous and famous animal of cat family found  in S. America ...	Puma",
				 "	The highest peak of Ecuador... 	Chimborazo", 
				 "	The forest along the western slopes of the Andes are known as... 	Montana",
				 "	The famous tree of Brazil which yield was... 	Carnauba plum tree", 
				 "	A surefooted strange animal of the South America... 	Llamas",
				 "	A smaller variety of llama found on the high plateau... 	Alpaca", 
				 "	A wild variety of llama found in the desert of Patagonia... 	Guanaco",
				 "	The lungs of the world... 	the Amazonian Rainforest",    
				 "	A large python found only in Amazon rainforests... 	Anaconda", 
				 "	The term used to describe Brazilian North East... 	Polygon of Drought", 
				 "	The largest river of the world... 	Amazon", 
				 "	The world’s most concentrated single source of natural manure... 	Guano Islands (off the cost of Peru) ",  
				 "	The largest producer of Nitrates 	Chile",
				 "	The richest mining areas of Brazil are in the state of 	Minas Gerais",  
				 "	The homeland of rubber 	Brazil", 
				 "	The Trans –Amazon Highway connects 	Rio Bronco to Sao Louis", 
				 "	Paraguay Tea is made from the leaves of 	Yerba",

				 
				 
				 
				 
				 
				 
				 
				 
				 "	Panama was once a province of...	 Colombia",
				 "	Mosquito coast is located in... 	Nicaragua",
				 "	Old capital of  Belize... 	Belize city",
				 "	The capital of Costa Rica, Honduras and El Salvador... 	San Jose, Tegucigalpa, San Salvador",
				 "	Republic of Haiti and Dominican  Republic share the Island of... 	Hispaniola",
				 "	Most populated C. American republic...	El Salvador",
				 "	The smallest C. American nation..	 El Salvador",
				 "	The largest urban agglomeration in the world... 	Mexico city", 
				 "	The only Middle American country where	 Olympics was held...	Mexico (1968) ",
				 "	One of the largest silver mines in the world...	 Chihuahua, Mexico",
				 "	The Islands of the Lesser Antilles once under British rule... Barbados,				 		St. Lucia, St. Vincent, Grenada",
				 "	The largest of the Middle American countries ... 	Mexico",
				 "	The country known for producing sugarcane, cigars and boxers...	 Cuba",
				 "	An island of the Greater Antilles which was a French colony...	 Haiti",
				 "	Chagres Locks, Pedro Miguel Lock and Miraflores	Locks are found on the ...	Panama Canal ",
				 "	The cities on the Pacific and  Atlantic ends of Panama Canal...	 Balboa, Colon respectively",
				 "	The largest export of Puerto Rico...	 Chemicals",
				 "	The largest export of most of the Carribbean islands... 	Sugarcane",
				 "	Country that was formerly called British Honduras...	 Belize",
				 "	The only C American country not having an Atlantic coastline... 	El Salvador",
				 "	The only C.American republic not having a Pacific coastline...	Belize",
				 "	President of one of the C. American republics who was arrested by the US on drug charges ... 	Manuel Noriega of Panama",
				 "	The Switzerland of Central America...	Costa Rica", 
				 "	The agricultural communities in Mexico, who hold the land collectively... 	Ejudos",
				 "	The canal which connects the Atlantic with Pacific Ocean...	Panama canal", 
				 "	The maximum number of Cubans outside Cuba is in...	Little Havana (Florida – USA) ",    
				 "	The native people of the Greater Antilles... 	Arawaks", 
				 "	The motive people of the lesser Antilles... 	Caribs",
				 "	Four largest Caribbean Islands forming the Greater Antilles... 	Cuba, Puerto Rio, Haiti and Jamaica   ",
				 "	Two most important countries included in the Lesser Antilles... 	Trinidad & Tobago and Barbados",

				 
				 
				 

				 
				 
				 
				 "	The discontiguous city of Russia... 	Kaliningrad ",
				 "	In descending order of size, the four islands of Japan... 	I- Honshu, II-Hokkaido, III-Kyushu, IV-Shikoku", 
				 "	The contribution of Japan in the total fishing haul of the world... 	15%",
				 "	The island on which the cities of Tokyo and Yokohama are located... 	Honshu",   
				 "	The most popular species of trees found in Japan...	1. Sugi (Cedor) 2. Hinoki (Cyprus) 3. Akamatsee (Red pine) ",  
				 "	The biggest trading partner of Japan... 	USA",
				 "	The tropical cyclone biting the southern coast of Japan frequently... 	Typhoons", 
				 "	The two important oil fields of Japan... 	Nigata, Akita", 
				 "	The southern island groups of Japan... 	Kerma Island",    
				 "	The roof of the Korean Peninsula... 	Korma Highlands", 
				 "	The deepest fresh water lake of the world... 	Lake Baikal", 
				 "	The countries forming Mukden triangle in China, the region of well developed iron and steel industry ...	1. Anshan 2. Fushun  3. Shenyang ",
				 "	The Sick Man of Europe... 	Turkey (Asia Minor) ",
				 "	The Switzerland of Middle East... 	Lebanon", 
				 "	The Land of Seven Hills... 	Jordan", 
				 "	The Land of Rivers and Distributaries... 	Bangladesh", 
				 "	The Country of Canals... 	Pakistan", 
				 "	World’s largest non-capital city... 	Shanghai", 
				 "	The steel capital of China...  	Anshan", 
				 "	The Detroit of Japan... 	Nagoya",  
				 "	The longest river of Asia... 	Chang Jiang", 
				 "	The life line of Myanmar... 	Irrawaddy",
				 "	The island which is known as the Rice Bowl of Philippines... 	Luzon", 
				 	"The land of thunder dragon”... 	Bhutan", 
				 "	The largest dam of Pakistan which is located on the Jhelum river... 	Mangla Dam", 
				 "	The longest river of Sri Lanka... 	Mahaweli Ganga", 
				 "	The only active volcano of Philippines... 	Mount Mayan", 
				 "	The three cities of Pakistan known for growing fruits... 	Chaman city, Quetta and Kalat", 
				 "	The twin ancient towns of Pakistan where  rivers of the Indus Valley civilization have been excavated... Harappa & Mohenjodaro ",
				 "	The only hydroelectric project of Bhutan with the help of India... 	Chukha Project ",
				 "	The largest sandy beach in the world located on the eastern coast of Bangladesh... 	Cox’s Bazaar", 
				 "	The famous tin and tungsten mines of Myanmar... 	Tanintharyi", 
				 "	The place where pearls are found in Myanmar... 	Gulf of Martaban", 
				 "	The city near Chindwinn... 	Myitaha confluence famous for coal deposits", 
				 "	The two districts of Bangladesh famous for Natural Gas... 	Comilla and Sychet", 
				 "	The two states of Malaysia located in the northern Borneo... 	Sarawak and Sabah",   
				 "	The Singapore of future... 	Pening", 
				 "	The land of golden Pagoda... 	Myanmar", 
				 "	The countries forming the golden triangle, the region known for opium cultivation... 	Laos, Myanmar and Thailand",
				 "	The city which is the world’s largest supplies of Cinchona for Quinine... 	Banlung ", 
				 "	The Balkan of East... 	S.E. Asia", 
				 "	The official language of Indonesia... 	Bhasa Indonesia", 
				 "	The home of green revolution... 	Philippines", 
				 "	The largest Peninsula of the world... 	Arabian Peninsula", 
				 "	The two countries of Asia which are also partly in Europe... 	Turkey and Russia", 
				 "	The key to Black Sea... 	Strait of Bosporus", 
				 "	The Paris of East... 	Beirut",
				 "	The Island of Pearl...  	Bahrain", 
				 "	The land of five Seas...  	Saudi Arabia", 
				 "	Countries having control over the strait of Bab-el-Mandeb... 	Yemen and Djibouti",  
				 "	Countries having control over the strait of Hormuz... 	Oman and Iran", 
				 "	The largest Salty desert of the world situated in the Northern Iran... 	Dasht-i-Kavir", 
				 "	The largest continuous sand desert in the southern port of Saudi Arabia which is also termed as Empty Quarter...	Rub-al-Khali ", 
				 "	The lowest point of the world... 	Dead Sea (400 m below sea level) ", 
				 "	The saltiest lake in the world... 	Lake Van (Turkey) ", 
				 "	The salt lake in China which is the site of numerous nuclear testing... 	Lake Lop Nor", 
				 "	The river which forms the boundary between Thailand and Cambodia... 	Mekong", 
				 "	The region which is known as the 'cross roads of culture'... 	S. E. Asia", 
				 "	The river which forms the boundary between Russia and China... 	Amur", 
				 "	The two major oil pipelines of Iran... 	I. Tehran – Abadan  II. Tehran – Shiraz", 
				 "	World’s longest artificial waterway from Beijing to Nanjing... 	Ground Canal", 
				 "	The mountain which divides China into North and South China... 	Quinling mountain", 
				 "	The channel which separates Andaman Nicobar islands from Sumatra... 	Great channel", 
				 "	The land of white elephant... 	Thailand", 
				 "	The largest Buddhist Temple... 	Borobudor (Java) ",
				 "	The top four countries in descending order of Muslim population... 	I. Indonesia II. India III. Bangladesh IV. Pakistan ",
				 "	The largest lake of S.E. Asia... 	Lake Tonlip Sap  ",
				 "	The countries forming Golden crescent, the region of illict opium cultivation... 	Pakistan, Afghanistan & Iran", 
				 "	Most famous offshore oil well of Burnei... 	Ampa",  
				 "	The island country of the Persian Gulf... 	Bahrain", 
				 "	The cultural capital of Iran... 	Shiraz", 
				 
				 
				 
				 
				 
				 
				 
				 
				 "	Plains of New Zealand famous for the dairy industry ...	Taranaki",
				 "	Region of inland drainage in Australia ...	Lake Eyre",
				 "	Natural fountains in Australia...	Great Artesian Wells",
				 "	Highest mountain peak in Australia ...	Mt. Kosciusko",
				 "	Strait between Australia and Tasmania ...	Bass Strait",
				 "	Great Barrier reef lies off the coast of ...	Queensland",
				 "	The longest tributary of Murray-Darling ...	Marambidgee",
				 "	Kalgoorlie is famous for ...	Gold Mining", 
				 "	An animal bird with 4 legs that lays eggs ...	Platypus",
				 "	National animal of Australia ...	Kangaroo",
				 "	Most industrialised state of Australia ....	Victoria",
				 "	Mt. Tom Price is famous for ...	Iron",
				 "	Lead-Zinc-Silver are mined at ... 	Mt. Isa and Broken Hills",
				 "	Weipa in Cape York Peninsula is famous for ...	Bauxite",
				 "	Australian Temperate Grasslands ...	Downs",
				 "	Strait between Australia and New Guinea ...	Torres Strait",
				 "	Trans-Australian railway runs between ...	Perth and Sydney",
				 "	Major roads in Australia are called ...	Commonwealth Highways",
				 "	City of Canberra was designed by ...	Walter Burley Griffin",
				 "	Outport of Perth ...	Freemantle",
				 "	Aborigines of Australia ...	Bindibus",
				 "	Canberra is located on river ...	Molonglo",
				 "	The city where 2000 Olympics were held ...	Sydneyv",
				 "	Dry interiors of Australia ...	Australian Outback",
				 "	The most populated of the Australian states ...	New South Wales",
				 "	Two federal territories of Australia ...	 Northern Territory;  Australian Capital Territory, Canberra",
				 "	Capital of Tasmania ...	Hobart",
				 "	Sheep rearing farms in Australia are called ...	Stations",
				 "	Gippsland is famous for ...	Petroleum",
				 "	The aborigines of New Zealand of Polynesian descent ...	Maoris",
				 "	The international airlines of Australia ...	Qantas Airways",
				 "	The southern most capital city of the world ...	Wellington",
				 "	Largest lake of Australia ...	Eyre",
				 "	The pride of Australia, Don Bradman, hails from the city of... Brisbane",
				 "	The strait between North & South Island of New Zealand...	Cook Strait",
				 "	The biggest city of New Zealand ...	Auckland",
				 "	The first European to discover New Zealand ...	Abel Tasman",
				 "	The most populous urban centre in New Zealand ...	Auckland",
				 "	The highest peak of New Zealand ...	Mt. Cook",
				 "	The chief farming region in New Zealand ...	Canterbury Plains",
				 "	The largest territory of New Zealand ...	South Island",
				 "	The highest uplifted coral island in the world ...	Niue",
				 "	The Australian states in decreasing order of population ...	I. New South Wales II Victoria III Queensland  IV Western Australia",
				 "	The largest state of Australia ...	Western Australia",
				 "	The Trans-Continental Stuart Highway of Australia connects  ...	Northern Territory and South Australia",
				 "	Australasia stands for ...	Australia and New Zealand",
				 "	The city of Australia known for lead-zinc and silver mines... 	Sydney", 
				 "	Capital and chief harbour of Queens land...	Brisbane", 
				 "	Centre of lignite and sub bituminous coal mining in Australia... Ipswich ",
				 "	The tree of Australia which yields golden flowers in summer... 	Wattle ",
				 "	Beside kangaroo, the other two famous marsupial of Australia... 	Koala & Wallby", 
				 "	The wild dog of Australia... 	Dingo", 
				 "	The laughing Jackass of Australia... 	Kookaburra",
				 "	The largest producer of Bauxite in the world... 	Australia", 
				 "	The labourers working in the sheep stations of Australia are known as... 	Jackaroos", 
				 "	The Australian province which has maximum number of sheep... 	New South Wales", 
				 "	The Australian province having highest number of cattle... Queens land ",
				 "	Two important varieties of Eucalyptus found in Australia... 	Jarrah and Karri ",
				 "	The country which generates 7% of its energy from geo-thermal springs... 	New Zealand", 
				 "	The most famous geysers of Maori town... 	Pohutu Geyser", 
				 "	The Australian cities in decreasing order of population... 	Sydney, Melbourne, Brisbane", 
				 "	The Australian Trans-Continental Railway connects... 	Sydney to Perth", 
				 "	The major roads in Australia are called... 	Commonwealth Highways",
				 "	A self-governing overseas territory of New Zealand... 	Niue", 
				 "	The first country to enfranchise women... 	New Zealand", 
				 "	The largest city of New Zealand... 	Auckland", 



	 };
}	 




		                      

